### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by 0815Creeper**
version bumps in github actions,
switch from artifacts to commit-based example upload,
check for example build success

### CODE REVIEW

**Comment by 0815Creeper** [comment]
ready to merge

**Comment by 0815Creeper** [comment]
now the failing examples use DifferentialEquations 7.13 but still failing due to (upgradable) BoundaryValueDiffEq v5.7.1
any further ideas?

**Comment by 0815Creeper** [comment]
will FMIFlux.jl move away from DifferentialEquations.jl (just as FMI.jl) soon or not? if not, this needs fixing

**Comment by ThummeTo** [comment]
see feature branch v0.13.0 :) 
(answer is yes, it's `OrdinaryDiffEq` now)

**Comment by 0815Creeper** [comment]
just found the possible source of the issue: some other recursive dependent packages, that prevent BoundaryValueDiffEq from updated. The only reasonable solution is to limit BoundaryValueDiffEq to 5.6 manually within the action. 
Not pretty but for now the best solution, I think

**Pull request merged**
